"use strict";

/////////////////////////////////////////////////////////////////////////////////////////////
const ContextMenuItems = [
	{
		id: "mnuTreeOpenFeed",
		class: "ctx-menu-item tree-item-ctx",
		text: i18n("js_contextMenuOpen"),
		shortcut: "o",
		accelerator: "O",
		group: 1,
	},
	{
		id: "mnuTreeOpenFeedNewTab",
		class: "ctx-menu-item tree-item-ctx",
		text: i18n("js_contextMenuOpenNewTab"),
		shortcut: "t",
		accelerator: "T",
		group: 1,
	},
	{
		id: "mnuTreeOpenFeedNewContainerTab",
		class: "ctx-menu-item tree-item-ctx",
		text: i18n("js_contextMenuOpenNewContainerTab"),
		shortcut: "b",
		accelerator: "B",
		group: 1,
	},
	{
		id: "mnuTreeOpenFeedNewWin",
		class: "ctx-menu-item tree-item-ctx",
		text: i18n("js_contextMenuOpenNewWin"),
		shortcut: "w",
		accelerator: "W",
		group: 1,
	},
	{
		id: "mnuTreeOpenFeedNewPrivateWin",
		class: "ctx-menu-item tree-item-ctx",
		text: i18n("js_contextMenuOpenNewPrivateWin"),
		shortcut: "v",
		accelerator: "V",
		group: 1,
	},
	{
		id: "mnuTreeOpenAllFeedsInNewTabs",
		class: "ctx-menu-item tree-item-folder-ctx",
		text: i18n("js_contextMenuOpenAllUnread"),
		shortcut: "a",
		accelerator: "A",
		group: 1,
	},
	{
		id: "mnuTreeSigninFeed",
		class: "ctx-menu-item tree-item-unauthorized-ctx",
		text: i18n("js_contextMenuSignin"),
		accelerator: "L",
		group: 2,
	},
	{
		id: "mnuTreeToggleFeedReadUnread",
		class: "ctx-menu-item tree-item-ctx tree-item-folder-ctx",
		text: i18n("js_contextMenuToggleReadUnread"),
		shortcut: "g",
		accelerator: "G",
		group: 3,
	},
	{
		id: "mnuTreeMarkAllFeedsRead",
		class: "ctx-menu-item tree-item-ctx tree-item-folder-ctx tree-ctx",
		text: i18n("js_contextMenuMarkAllRead"),
		shortcut: "r",
		accelerator: "R",
		group: 4,
	},
	{
		id: "mnuTreeMarkAllFeedsUnread",
		class: "ctx-menu-item tree-item-ctx tree-item-folder-ctx tree-ctx",
		text: i18n("js_contextMenuMarkAllUnread"),
		shortcut: "u",
		accelerator: "U",
		group: 4,
	},
	{
		id: "mnuTreeNewFeed",
		class: "ctx-menu-item tree-item-ctx tree-item-folder-ctx tree-ctx",
		text: i18n("js_contextMenuNewFeed"),
		shortcut: "n",
		accelerator: "N",
		group: 5,
	},
	{
		id: "mnuTreeNewFolder",
		class: "ctx-menu-item tree-item-ctx tree-item-folder-ctx tree-ctx",
		text: i18n("js_contextMenuNewFolder"),
		shortcut: "f",
		accelerator: "F",
		group: 5,
	},
	{
		id: "mnuTreeCopyFeedUrl",
		class: "ctx-menu-item tree-item-ctx",
		text: i18n("js_contextMenuCopyLink"),
		shortcut: "c",
		accelerator: "C",
		group: 5,
		},
	{
		id: "mnuTreePasteFeedUrl",
		class: "ctx-menu-item tree-item-ctx tree-item-folder-ctx tree-ctx",
		text: i18n("js_contextMenuPasteLink"),
		shortcut: "s",
		accelerator: "S",
		group: 5,
	},
	{
		id: "mnuTreeDeleteTreeItem",
		class: "ctx-menu-item tree-item-ctx tree-item-folder-ctx",
		text: i18n("js_contextMenuDelete"),
		shortcut: "d",
		accelerator: "D",
		group: 5,
	},
	{
		id: "mnuTreeProperties",
		class: "ctx-menu-item tree-item-ctx tree-item-folder-ctx",
		text: i18n("js_contextMenuProperties"),
		shortcut: "p",
		accelerator: "P",
		group: 6,
	},
	{
		id: "mnuTreeSummary",
		class: "ctx-menu-item tree-item-ctx tree-item-folder-ctx tree-ctx",
		text: i18n("js_contextMenuSummary"),
		shortcut: "m",
		group: 7,
	},
	{
		id: "mnuTreeSwitchDirection",
		class: "ctx-menu-item tree-item-ctx tree-item-folder-ctx tree-ctx",
		text: i18n("js_contextMenuSwitchDirection"),
		shortcut: "i",
		group: 8,
	},
	{
		id: "mnuListOpenFeedItem",
		class: "ctx-menu-item list-item-ctx",
		text: i18n("js_contextMenuOpen"),
		shortcut: "o",
		accelerator: "O",
		group: 9,
	},
	{
		id: "mnuListOpenFeedItemNewTab",
		class: "ctx-menu-item list-item-ctx",
		text: i18n("js_contextMenuOpenNewTab"),
		shortcut: "t",
		accelerator: "T",
		group: 9,
	},
	{
		id: "mnuListOpenFeedItemNewReaderTab",
		class: "ctx-menu-item list-item-ctx",
		text: i18n("js_contextMenuOpenNewReaderTab"),
		shortcut: "e",
		accelerator: "E",
		group: 9,
	},
	{
		id: "mnuListOpenFeedItemNewContainerTab",
		class: "ctx-menu-item list-item-ctx",
		text: i18n("js_contextMenuOpenNewContainerTab"),
		shortcut: "b",
		accelerator: "B",
		group: 9,
	},
	{
		id: "mnuListOpenFeedItemNewWin",
		class: "ctx-menu-item list-item-ctx",
		text: i18n("js_contextMenuOpenNewWin"),
		shortcut: "w",
		accelerator: "W",
		group: 9,
	},
	{
		id: "mnuListOpenFeedItemNewPrivateWin",
		class: "ctx-menu-item list-item-ctx",
		text: i18n("js_contextMenuOpenNewPrivateWin"),
		shortcut: "v",
		accelerator: "V",
		group: 9,
	},
	{
		id: "mnuListOpenAllFeedItemsTabs",
		class: "ctx-menu-item list-item-ctx list-ctx",
		text: i18n("js_contextMenuOpenAllUnread"),
		shortcut: "a",
		accelerator: "A",
		group: 9,
	},
	{
		id: "mnuListToggleFeedItemReadUnread",
		class: "ctx-menu-item list-item-ctx",
		text: i18n("js_contextMenuToggleReadUnread"),
		shortcut: "g",
		accelerator: "G",
		group: 10,
	},
	{
		id: "mnuListMarkAllFeedItemsRead",
		class: "ctx-menu-item list-item-ctx list-ctx",
		text: i18n("js_contextMenuListMarkAllRead"),
		shortcut: "r",
		accelerator: "R",
		group: 11,
	},
	{
		id: "mnuListMarkAllFeedItemsUnread",
		class: "ctx-menu-item list-item-ctx list-ctx",
		text: i18n("js_contextMenuListMarkAllUnread"),
		shortcut: "u",
		accelerator: "U",
		group: 11,
	},
	{
		id: "mnuListCopyFeedItemUrl",
		class: "ctx-menu-item list-item-ctx",
		text: i18n("js_contextMenuCopy"),
		shortcut: "c",
		accelerator: "C",
		group: 12,
	},
	{
		id: "mnuListSwitchDirection",
		class: "ctx-menu-item list-item-ctx list-ctx",
		text: i18n("js_contextMenuSwitchDirection"),
		shortcut: "i",
		group: 13,
	},
];
