"use strict";

/////////////////////////////////////////////////////////////////////////////////////////////
const SidebarContextMenuItems = [
	{
		id: "mnuTreeOpenFeed",
		class: "ctx-menu-item tree-item-ctx",
		text: "Open",
		shortcut: "o",
		accelerator: "O",
		group: 1,
	},
	{
		id: "mnuTreeOpenFeedNewTab",
		class: "ctx-menu-item tree-item-ctx",
		text: "Open in New Tab",
		shortcut: "t",
		accelerator: "T",
		group: 1,
	},
	{
		id: "mnuTreeOpenFeedNewContainerTab",
		class: "ctx-menu-item tree-item-ctx",
		text: "Open in New Container Tab...",
		shortcut: "b",
		accelerator: "B",
		group: 1,
	},
	{
		id: "mnuTreeOpenFeedNewWin",
		class: "ctx-menu-item tree-item-ctx",
		text: "Open in New Window",
		shortcut: "w",
		accelerator: "W",
		group: 1,
	},
	{
		id: "mnuTreeOpenFeedNewPrivateWin",
		class: "ctx-menu-item tree-item-ctx",
		text: "Open in New Private Window",
		shortcut: "v",
		accelerator: "V",
		group: 1,
	},
	{
		id: "mnuTreeOpenAllFeedsInNewTabs",
		class: "ctx-menu-item tree-item-folder-ctx",
		text: "Open All Unread in Tabs",
		shortcut: "a",
		accelerator: "A",
		group: 1,
	},
	{
		id: "mnuTreeSigninFeed",
		class: "ctx-menu-item tree-item-unauthorized-ctx",
		text: "Sign in...",
		accelerator: "L",
		group: 2,
	},
	{
		id: "mnuTreeToggleFeedReadUnread",
		class: "ctx-menu-item tree-item-ctx tree-item-folder-ctx",
		text: "Toggle Read/Unread",
		shortcut: "g",
		accelerator: "G",
		group: 3,
	},
	{
		id: "mnuTreeMarkAllFeedsRead",
		class: "ctx-menu-item tree-item-ctx tree-item-folder-ctx tree-ctx",
		text: "Mark All Tree Feeds as Read",
		shortcut: "r",
		accelerator: "R",
		group: 4,
	},
	{
		id: "mnuTreeMarkAllFeedsUnread",
		class: "ctx-menu-item tree-item-ctx tree-item-folder-ctx tree-ctx",
		text: "Mark All Tree Feeds as Unread",
		shortcut: "u",
		accelerator: "U",
		group: 4,
	},
	{
		id: "mnuTreeNewFeed",
		class: "ctx-menu-item tree-item-ctx tree-item-folder-ctx tree-ctx",
		text: "New Feed...",
		shortcut: "n",
		accelerator: "N",
		group: 5,
	},
	{
		id: "mnuTreeNewFolder",
		class: "ctx-menu-item tree-item-ctx tree-item-folder-ctx tree-ctx",
		text: "New Folder...",
		shortcut: "f",
		accelerator: "F",
		group: 5,
	},
	{
		id: "mnuTreeCopyFeedUrl",
		class: "ctx-menu-item tree-item-ctx",
		text: "Copy Link",
		shortcut: "c",
		accelerator: "C",
		group: 5,
		},
	{
		id: "mnuTreePasteFeedUrl",
		class: "ctx-menu-item tree-item-ctx tree-item-folder-ctx tree-ctx",
		text: "Paste Link",
		shortcut: "s",
		accelerator: "S",
		group: 5,
	},
	{
		id: "mnuTreeDeleteTreeItem",
		class: "ctx-menu-item tree-item-ctx tree-item-folder-ctx",
		text: "Delete...",
		shortcut: "d",
		accelerator: "D",
		group: 5,
	},
	{
		id: "mnuTreeProperties",
		class: "ctx-menu-item tree-item-ctx tree-item-folder-ctx",
		text: "Properties...",
		shortcut: "p",
		accelerator: "P",
		group: 6,
	},
	{
		id: "mnuTreeSummary",
		class: "ctx-menu-item tree-item-ctx tree-item-folder-ctx tree-ctx",
		text: "Summary...",
		shortcut: "m",
		group: 7,
	},
	{
		id: "mnuTreeSwitchDirection",
		class: "ctx-menu-item tree-item-ctx tree-item-folder-ctx tree-ctx",
		text: "Switch View Direction",
		shortcut: "i",
		group: 8,
	},
	{
		id: "mnuListOpenFeedItem",
		class: "ctx-menu-item list-item-ctx",
		text: "Open",
		shortcut: "o",
		accelerator: "O",
		group: 9,
	},
	{
		id: "mnuListOpenFeedItemNewTab",
		class: "ctx-menu-item list-item-ctx",
		text: "Open in New Tab",
		shortcut: "t",
		accelerator: "T",
		group: 9,
	},
	{
		id: "mnuListOpenFeedItemNewContainerTab",
		class: "ctx-menu-item list-item-ctx",
		text: "Open in New Container Tab...",
		shortcut: "b",
		accelerator: "B",
		group: 9,
	},
	{
		id: "mnuListOpenFeedItemNewWin",
		class: "ctx-menu-item list-item-ctx",
		text: "Open in New Window",
		shortcut: "w",
		accelerator: "W",
		group: 9,
	},
	{
		id: "mnuListOpenFeedItemNewPrivateWin",
		class: "ctx-menu-item list-item-ctx",
		text: "Open in New Private Window",
		shortcut: "v",
		accelerator: "V",
		group: 9,
	},
	{
		id: "mnuListOpenAllFeedItemsTabs",
		class: "ctx-menu-item list-item-ctx list-ctx",
		text: "Open All Unread in Tabs",
		shortcut: "a",
		accelerator: "A",
		group: 9,
	},
	{
		id: "mnuListToggleFeedItemReadUnread",
		class: "ctx-menu-item list-item-ctx",
		text: "Toggle Read/Unread",
		shortcut: "g",
		accelerator: "G",
		group: 10,
	},
	{
		id: "mnuListMarkAllFeedItemsRead",
		class: "ctx-menu-item list-item-ctx list-ctx",
		text: "Mark All as Read",
		shortcut: "r",
		accelerator: "R",
		group: 11,
	},
	{
		id: "mnuListMarkAllFeedItemsUnread",
		class: "ctx-menu-item list-item-ctx list-ctx",
		text: "Mark All as Unread",
		shortcut: "u",
		accelerator: "U",
		group: 11,
	},
	{
		id: "mnuListCopyFeedItemUrl",
		class: "ctx-menu-item list-item-ctx",
		text: "Copy",
		shortcut: "c",
		accelerator: "C",
		group: 12,
	},
	{
		id: "mnuListSwitchDirection",
		class: "ctx-menu-item list-item-ctx list-ctx",
		text: "Switch View Direction",
		shortcut: "i",
		group: 13,
	},
];
